/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.1.112 */
/* Module Version: 5.7 */
/* Wed Nov 29 00:28:55 2017 */

/* parameterized module instance */
main_pll __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
