//   ==================================================================
//   >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
//   ------------------------------------------------------------------
//   Copyright (c) 2006-2011 by Lattice Semiconductor Corporation
//   ------------------------------------------------------------------
//   ALL RIGHTS RESERVED
//
//   IMPORTANT: THIS FILE IS AUTO-GENERATED BY THE LATTICEMICO SYSTEM.
//
//   Permission:
//
//      Lattice Semiconductor grants permission to use this code
//      pursuant to the terms of the Lattice Semiconductor Corporation
//      Open Source License Agreement.
//
//   Disclaimer:
//
//      Lattice Semiconductor provides no warranty regarding the use or
//      functionality of this code. It is the user's responsibility to
//      verify the user’s design for consistency and functionality through
//      the use of formal verification methods.
//
//   --------------------------------------------------------------------
//
//                  Lattice Semiconductor Corporation
//                  5555 NE Moore Court
//                  Hillsboro, OR 97214
//                  U.S.A
//
//                  TEL: 1-800-Lattice (USA and Canada)
//                         503-286-8001 (other locations)
//
//                  web: http://www.latticesemi.com/
//                  email: techsupport@latticesemi.com
//
//   --------------------------------------------------------------------
//
//      Project:           mico_cpu
//      File:              mico_cpu_inst.v
//      Date:              ×ò, 30 íîÿ 2017 06:19:32 YEKT
//      Version:           2.1
//      Targeted Family:   MachXO2
//
//   =======================================================================

mico_cpu mico_cpu_u ( 
.clk_i(clk_i),
.reset_n(reset_n)
, .sramsram_wen(sramsram_wen) // 
, .sramsram_data(sramsram_data) // [8-1:0]
, .sramsram_addr(sramsram_addr) // [19-1:0]
, .sramsram_csn(sramsram_csn) // 
, .sramsram_be(sramsram_be) // [1-1:0]
, .sramsram_oen(sramsram_oen) // 
, .gpioPIO_OUT(gpioPIO_OUT) // [32-1:0]
);
